# Generated by Django 3.2 on 2021-05-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_fund', models.CharField(max_length=50)),
                ('rooms_count', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(max_length=50)),
                ('balcony', models.BooleanField()),
                ('parking_space', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
